services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnishard-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - omnishard-network

  # Redis for Shard Mapping & Bloom Filter
  redis:
    image: redis:alpine
    container_name: omnishard-redis
    ports:
      - "6379:6379" # DBeaver/Redis Insight এর জন্য
    networks:
      - omnishard-network

  # Central Metadata Database
  metadata_db:
    image: mysql:8.0
    container_name: omnishard-metadata
    environment:
      MYSQL_DATABASE: metadata_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - omnishard-network

  # Shard 1 - Master
  shard_1:
    image: mysql:8.0
    container_name: omnishard-shard-1
    environment:
      MYSQL_DATABASE: shard_1_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - omnishard-network

  # Shard 1 - Replica
  shard_1_replica:
    image: mysql:8.0
    container_name: omnishard-shard-1-replica
    environment:
      MYSQL_DATABASE: shard_1_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - omnishard-network

  # Shard 2 - Master
  shard_2:
    image: mysql:8.0
    container_name: omnishard-shard-2
    environment:
      MYSQL_DATABASE: shard_2_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    networks:
      - omnishard-network

  # Shard 2 - Replica (নতুন যোগ করা হয়েছে)
  shard_2_replica:
    image: mysql:8.0
    container_name: omnishard-shard-2-replica
    environment:
      MYSQL_DATABASE: shard_2_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    networks:
      - omnishard-network

networks:
  omnishard-network:
    driver: bridge